FROM randomdude/gcc-cross-x86_64-elf

WORKDIR /usr/app

ARG IMAGE_NAME
ARG DEBUG
ARG DISPLAY

COPY ./src ./src
COPY ./Makefile .

RUN apt-get -y install nasm make

RUN touch .env
RUN echo "IMAGE_NAME=${IMAGE_NAME}\nDEBUG=${DEBUG}\nDISPLAY=${DISPLAY}\nENVIRONMENT=native" >> .env
RUN cat .env

RUN make

RUN mkdir -p /build && cp -r build/* /build